name: cbe_expense
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_storage: ^12.4.5
  firebase_app_check: ^0.3.2+5
  cloud_firestore: ^5.6.6
  feather_icons: ^1.2.0
  flutter_secure_storage: ^9.2.4
  intl: ^0.20.2
  another_telephony: ^0.4.1
  provider: ^6.1.4
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  fonts:
    - family: WinkyRough
      fonts:
        - asset: font/WinkyRough-Regular.ttf
    - family: LexendDeca
      fonts:
        - asset: font/LexendDeca-Regular.ttf
        - asset: font/LexendDeca-Bold.ttf
          weight: 700
